---
# tasks file

- name: Deploy amersports servers
  hosts: all
  vars:
    ansistrano_deploy_from: "{{ deploy_from }}"
    ansistrano_deploy_to: "{{ deploy_to }}"
    ansistrano_keep_releases: "{{ keep_releases }}"
    ansistrano_shared_paths:
      - "var"
      - "media"
  roles:
    - { role: carlosbuenosvinos.ansistrano-deploy }